<table border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <strong><?php echo $this->__('Website Id'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getWebsite()->getId(); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Website Name'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getWebsite()->getName(); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Store Id'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getStore()->getGroupId(); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Store Name'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getStore()->getGroup()->getName(); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Store View Id'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getStore()->getId(); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Store View Code'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getStore()->getCode(); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Store View Name'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getStore()->getName(); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Cache Method'); ?>:</strong>
    </td>
    <td>
      <?php echo $this->getCacheMethod(); ?>
    </td>
  </tr>
</table>