<?php 
$_helper = Mage::helper('wee_developertoolbar');
$_timers = $this->getTimers();
$i = 0;
?>

<table class="profilerTable" border="0" cellpadding="0" cellspacing="0">
  <tr class="head">
    <td><?php echo $this->__('Name'); ?></td>
    <td><?php echo $this->__('Time'); ?></td>
    <td><?php echo $this->__('Cnt'); ?></td>
    <td><?php echo $this->__('Emalloc'); ?></td>
    <td><?php echo $this->__('RealMem'); ?></td>
  </tr>
  <?php foreach ($_timers as $name => $value): ?>
      <?php 
        $sum = Varien_Profiler::fetch($name,'sum');
        $count = Varien_Profiler::fetch($name,'count');
        $realmem = Varien_Profiler::fetch($name,'realmem');
        $emalloc = Varien_Profiler::fetch($name,'emalloc');
        if ($sum<.0010 && $count<10 && $emalloc<10000) {
          continue;
        }
       ?>
      <tr class="<?php echo ($i % 2 ? 'even' : 'odd'); ?>">
        <td><?php echo $name; ?></td>
	    <td><?php echo number_format($sum,4); ?></td>
	    <td><?php echo $count; ?></td>
	    <td><?php echo number_format($emalloc); ?></td>
	    <td><?php echo $_helper->formatBytes($realmem); ?></td>
	  </tr>
    <?php $i++; ?>
  <?php endforeach ?>
</table>
