<div class="weeDeveloperToolbar" id="weeDeveloperToolbarContainer">
  <img class="magentoLogo" src="<?php echo Mage::getDesign()->getSkinUrl('images/wee_developertoolbar/logo.png'); ?>" alt="" />
    <?php if ($this->getItems()): ?>
    <ul id="weeDeveloperToolbar">
        <?php foreach ($this->getItems() as $item): ?>
          <?php echo $item->render(); ?>
        <?php endforeach ?>
    </ul>
    <?php endif ?>
</div>

<?php foreach ($this->getItems() as $item): ?>
  <?php if ($item->getContent()): ?>
    <div class="weeDeveloperToolbarDetails" id="weeDeveloperToolbarDetails_<?php echo $item->getName(); ?>" style="display:none;">
      <?php echo $item->renderContent(); ?>
    </div>
  <?php endif ?>
<?php endforeach ?>
